// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBzKW6X4B8ZRP4dmuuhfO2XlywiOX5LQs',
    appId: '1:431105590573:web:94e6355d8f15e0aa9dffa4',
    messagingSenderId: '431105590573',
    projectId: 'instagram-clone-af164',
    authDomain: 'instagram-clone-af164.firebaseapp.com',
    storageBucket: 'instagram-clone-af164.appspot.com',
    measurementId: 'G-HWKB4G5374',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyBMkzP03SXizeQsrWxCS-Cec5-9dHM1M',
    appId: '1:431105590573:android:1014ed9ccfef78449dffa4',
    messagingSenderId: '431105590573',
    projectId: 'instagram-clone-af164',
    storageBucket: 'instagram-clone-af164.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYN6tzk_IiiPPy_sAwiTXYk_v3P6g3TtE',
    appId: '1:431105590573:ios:e9b967d7915a75339dffa4',
    messagingSenderId: '431105590573',
    projectId: 'instagram-clone-af164',
    storageBucket: 'instagram-clone-af164.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYN6tzk_IiiPPy_sAwiTXYk_v3P6g3TtE',
    appId: '1:431105590573:ios:08b5ed0ee131429b9dffa4',
    messagingSenderId: '431105590573',
    projectId: 'instagram-clone-af164',
    storageBucket: 'instagram-clone-af164.appspot.com',
    iosBundleId: 'com.example.instagramClone.RunnerTests',
  );
}
